ciphers:
  mickey:
    key: 0xab8322676fd1333f160a #80bits = 20 hex digits
    iv: 0xa7a36548a932c54a0cfc

imageInput: c:/foto/foto.jpg
imageEncrypted: c:/foto/encrypted.jpeg
imageDecripted: c:/foto/decripted.jpeg
txtEncrypted: c:/foto/encrypted.txt
txtDecripted: c:/foto/decripted.txt